### ISSUE TITLE
Some input regarding generation node, regtest, ...

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#1]
Just yesterday I stumbled upon your [talk about unit and regtests tests](https://www.youtube.com/watch?v=wuJzMTDTj4A) and I was quite impressed.

I noticed a few points you mentioned:

- the use of shell scripts
- preserving an initial state, so it's not required to regenerate the first 100+ blocks on every run
- the initial Bitcoins are associated with "accounts"

Very recently, I think, Bitcoin Core master basically build a [Python framework for regtests](https://github.com/bitcoin/bitcoin/tree/master/qa/rpc-tests) that takes care of a few things in particular:

- nodes are spawned via Python and they are completely isolated
- on the first startup 200 blocks are generated and the results are stored in ./cache
- those results are then copied and reused to working dirs /tmp/testXXX for each node
- after a test run, the temporary files /tmp/testXXX are deleted

My initial goal was to port the few regtests of Master Core v0.0.8, but I ended up modifiying the framework and basically hacked a [Master Core regtest framework](https://github.com/dexX7/mastercore-rpc-tests) together. In the context of above:

- I use one [single node to generate blocks](https://github.com/dexX7/mastercore-rpc-tests/blob/master/util.py#L116-L119) and properties. If another node needs some BTC, then this node is used as provider. I decided this is cleaner than letting all four nodes (as per default with the core framework) generating blocks.
- I added a method that [collects all unspent outputs](https://github.com/dexX7/mastercore-rpc-tests/blob/master/framework_entity.py#L34-L55) and then sends them to an address to get full control and get rid of those Bitcoin "accounts".

I haven't explored bitcoin-spock yet (unfortunately!), and I'm not sure, if this is of any help, but wanted to let you know as soon as possible. :)

Regarding consensus hashes, I started https://github.com/mastercoin-MSC/mastercore/issues/143 some time ago.

**Comment by msgilligan** [comment]
I think it's time to close this issue. @dexX7 is there anything in here that warrants leaving this open or creating new issues?

**Comment by dexX7** [comment]
Yes, can be closed.
