### ISSUE TITLE
Refactor RegTest tests into package groups

### ISSUE THREAD

**Issue by msgilligan** [msgilligan/bitcoin-spock#13]
This Issue assumes that Issue #12 will be completed first, although the same basic reorganization could be done in sub packages of `org.mastercoin`.

Currently all the useful Omni Protocol RegTest tests are in the `org.mastercoin.test.rpc` package. I propose a new package hierarchy to improve reporting.  Something like:

* `foundation.omni.test.rpc.sto` - Send To Owners tests
* `foundation.omni.test.rpc.dex` - Distributed Exchange tests
* `foundation.omni.test.rpc.basic` - basic tests of RPC functions
* `foundation.omni.test.rpc.misc` - miscellaneous tests using RPC

This will allow us to view Jenkins reports at the package level and focus on a particular category of tests like "STO".

Currently the test Specs are all lumped together in a single package, generating [this report](http://ci.omni.foundation/job/msc-integ-regtest/lastCompletedBuild/testReport/org.mastercoin.test.rpc/). Adding an extra level of hierarchy here should make things more logical and allow us to write documentation with links to the reports for just one package, such as "STO".

**Comment by msgilligan** [comment]
With STO, I'm imagining we could have something like:

* STOBasicSuccessCasesSpec
* STOExpectedErrorCasesSpec
* STODataDrivenTestSpec
* STOReservedBalancesSpec
* STOBlockchainReorgTestSpec (maybe this would be in a different package of re-org tests)

**Comment by dexX7** [comment]
I really like the report Groovy/Spock creates, and it would be great, if it were exported by default.

Even though the test plan can be splitted into groups such as "reserved balances" and "transaction ordering", in the end the actual tests are likely the same, but executed on another set of input data. At least that's my impression at the very moment. If we can group it into logical groups, I would really like it though.

**Comment by msgilligan** [comment]
@dexX7 I created Issue #15 for exporting/publishing the Spock test report. The latest report for each job is available in the "workspace" of each job for users with accounts on the CI server.

**Comment by msgilligan** [comment]
Implemented in commit e2d55a448a4025fd0b1f0b991a577808a494573e.
