### ISSUE TITLE
MSCSendToOwnersTestPlanSpec: invalidation tests

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#18]
To keep track of the progress:

We need to test two things: creating a transaction via the RPC interface with `sendtoowners_MP` and creating transactions as raw transactions to get around sanity checks on the RPC layer.

**Comment by marv-engine** [comment]
Yes, we need to confirm that behavior is correct for all ways to create the transactions.

**Comment by dexX7** [comment]
@marv-engine: some user input should be rejected on the RPC layer, for example: it is never valid to use BTC as property for a STO transaction, but other user input is strictly seen impossible to validate at this point, for example whether the user has a sufficient balance when the transaction is actually processed, or if a property exists.

Now despite what Master Core currently does: what would you expect to be rejected on the RPC layer?

**Comment by marv-engine** [comment]
What I want to confirm is that invalid transactions are detected and rejected regardless of how they are submitted. Plus, we should confirm that valid transactions are accepted and interpreted correctly and then processed correctly, again regardless of how they are submitted.

**Comment by dexX7** [comment]
I'm currently working on creating raw transactions which are injected into the blockchain, so to speak, to bypass the RPC layer and to confirm correct validation/invalidation and handling on the parsing/interpretation layer. When fetching those transaction via `gettransaction_MP` the field `valid` should be `false` for all invalidation tests.

When submitting the transactions via RPC, for example with `sendtoowners_MP`, then there are additional checks in place: non-existing properties or an amount of zero is rejected right at this point, without getting the transaction into the blockchain at all.

Some checks are impossible to do on the RPC layer though. For example, it's impossible to know how many owners there are *at the time when the transaction is processed*, so it's impossible to determine the actual fee in advance, and therefore it's also impossible to determine, whether the sender has a sufficient balance. Because of this, there are no balance checks on the RPC layer at all.

I wanted to confirm this behavior matches your expectation, as it determines which tests should be checked explicitly for exceptions/rejections when using `sendtoowners_MP`.

**Comment by marv-engine** [comment]
@dexX7 yes, that sounds right. Errors that can be detected at submission should be rejected at that point.

**Comment by msgilligan** [comment]
@dexX7 Note that we can use bitcoinj to send raw transactions via P2P protocol rather than using `sendrawtx_MP()` -- that path *may* (I don't know the Bitcoin Core / Omni Core code well enough) may be even more independent of any checking done by the Omni code.

Look at the method (feature) named `"create and send a transaction from BitcoinJ using wallet.completeTx"()` in `com.msgilligan.bitcoinj.WalletSendSpec`. I wrote it months ago and haven't tested it (don't even remember if it was working) but it is an approach that should use P2P.

We could even go so far as to run an unmodified bitcoind in RegTest mode connected to Omni Core and have that bitcoind instance write the block.

**Comment by dexX7** [comment]
@msgilligan: at some point maybe, but `sendrawtx_MP` does not only construct and broadcast a transaction, but also obfuscates and embeds the raw Omni transaction data.

**Comment by msgilligan** [comment]
@dexX7: Agreed, doesn't sound like a high priority.

**Comment by dexX7** [comment]
@msgilligan: some feedback regarding the general direction would be appreciated:

https://github.com/dexX7/bitcoin-spock/compare/wip-sto-invalidation?expand=1

It builds upon https://github.com/msgilligan/bitcoin-spock/pull/21, which mostly doesn't change functionality, but focuses on types, labels etc.

I then moved the "skip test" checks as temporary workaround into:
```groovy
def maybeSkipInvalidationTests(...)
def maybeSkipReservedAmountsTests(...)
```

And extracted the "send to owners" action:
```groovy
def executeSendToOwners(Address actorAddress, ...)
```

The idea I had was to have a base class and one or more sub-classes which handle the actual send, and maybe other parts, differently.

The following doesn't skip the invalidation tests and overrides `executeSendToOwners` and to bypass the RPC interface `createSendToOwnersHex` and `sendrawtx_MP` are used:

```groovy
/**
 * Data driven tests for the "send to owners" transaction type, whereby a raw
 * transaction is created and broadcasted to bypass the RPC interface
 */
class MSCSendToOwnersTestPlanRawSpec extends MSCSendToOwnersTestPlanSpec
```

This works fine so far, except for the very special cases where BTC is involved or the property identifier doesn't exist. Test plan L13, L14 fail as well, but they need special handling, too.

Maybe it's best to modularize each step, for example:

1. prepare properties
2. fund actor
3. fund owners
4. send to owners
5. ...

And then create a few sub-classes for different test types such as "test everything with raw transactions", or the ones for the special cases, or one where explicit throwing of exceptions is expected.

To target specific parts of the test plan, the plan could be splitted and I created `getTestPlanPath()` to support other input data in the sub-classes.

**Comment by dexX7** [comment]
@marv-engine: I tend to remove the following test:

> Sender owns all the coins of the STO Property, other addresses had non-zero balances but now zero balances

Because the additional constraint doesn't fit into a batch test. Likewise:

> STO Property ID is non-existent
> STO Property ID is 0 (bitcoin)

I tested what I outlined above, but ended up with a lot of helper methods and it's very difficult to read, so I suggest to limit the test plan tests to those with a similar structure and test the others seperately.

**Comment by msgilligan** [comment]
I definitely prefer separate tests to keep things as clean and simple as possible.

**Comment by dexX7** [comment]
The remaining missing tests are:

- STO Property ID is 0 - bitcoin
- STO Property ID is non-existent
- Sender owns all the coins of the STO Property, other addresses had non-zero balances but now zero balances

**Comment by dexX7** [comment]
Finished by #36, #37.
