### ISSUE TITLE
Where can we see the detailed results/output of each test?

### ISSUE THREAD

**Issue by marv-engine** [msgilligan/bitcoin-spock#19]

**Comment by dexX7** [comment]
Yes, this is possible. Please take a look at:

http://bitwatch.co/uploads/sto-test-plan-f17086b645/classes/org.mastercoin.test.rpc.MSCSendToOwnersTestSpec.html

This was an earlier attempt where I included results in the title. Right now the "description" is used. Basically all fields as well as basic operations on those fields (e.g. "sum owners available amounts") can be used from the spreadsheet:

https://github.com/msgilligan/bitcoin-spock/blob/master/src/integ/groovy/foundation/omni/test/rpc/sto/sto-testplan.tsv

What would you like to have in the title?

**Comment by marv-engine** [comment]
I was referring to the Spock output that shows the assertions with the values being used for the test. This is to satisfy my desire to see that the correct input values are being used and that the expected outputs are being produced.

**Comment by dexX7** [comment]
Ah I see. It's certainly possible to simply print the values, which should be visible in the Jenkins environment as "test output". However, the "nice spock output" is only shown, when a test fails.

There is [only one test file](https://github.com/msgilligan/bitcoin-spock/blob/master/src/integ/groovy/foundation/omni/test/rpc/sto/MSCSendToOwnersTestPlanSpec.groovy) which operates on the whole spreadsheet. The `assert` and `==` are the underlying assertions applied, whereby the titles (`when`, `then`, ...) are just visual hints.

Maybe @msgilligan has some further input on this.

**Comment by msgilligan** [comment]
"I just noticed the visual hints do currently not reflect the correct column names." I'm assuming that what you're saying here is that the String comments following the `when` and `then` labels are not getting their #variables substituted by Spock's `@Unroll` feature. I'm not sure if there's anyplace where those comments are every displayed "per test" in such a way the substitution could be applied.

**Comment by dexX7** [comment]
I was referring to the String comments, yes, but in relation to the column names. They currently refer to the old sheet, for example:

```groovy
when: "#stoAmountSP is sent to owners of #currencySP"
```

... whereby with updated column names it should be:

```groovy
when: "#AmountSTO is sent to owners of #currencySP"
````

**Comment by msgilligan** [comment]
I see, @dexX7.

I don't think those variables (e.g. `#amountSTO`) are ever actually substituted -- unless somewhere in the woods where there's no one to hear it ;)  Thought using the `#` variables is still a good documentation practice, it seems.

**Comment by msgilligan** [comment]
For the Omni project, I think this question is best answered on the [Jenkins page](https://github.com/mastercoin-MSC/omni-devops/blob/master/adoc/jenkins.adoc) of the [mastercoin-MSC/omni-devops](https://github.com/mastercoin-MSC/omni-devops) project.

**Comment by msgilligan** [comment]
@marv-engine Given the above comment, can we close this issue?
