### ISSUE TITLE
MSCSendToOwnersConsensusComparisonSpec: before is null

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#26]
Now this is odd behavior that I can't explain:

When running MSCSendToOwnersConsensusComparisonSpec as single test, then everything appear to be fine.\*

When running all RegTest tests (parameter: "--tests com.msgilligan.bitcoin.rpc.* --tests foundation.omni.test.rpc.*"), then it fails for one address. This is the case with the master branch, but also with my feature branch. The reason is that "before" is null:

![spock-consensus](https://cloud.githubusercontent.com/assets/5836089/5880162/3e8c5160-a336-11e4-9303-8e08ec73d025.png)

This only happens sometimes and I haven't yet found a way to reproduce this issue at a 100 % rate.

\*Because I'm not sure, how to reproduce this, there might not be a relation to whether I run the test individually or in a batch.

Edit: I took a look at a [previous test report](http://bitwatch.co/uploads/sto-test-plan-5bb69c0/classes/foundation.omni.test.rpc.sto.MSCSendToOwnersConsensusComparisonSpec.html#mkiNtbm51SQrHWHbjJ2jEbaoQWJgS946ec) and in both cases it involves an address with reserved amount.

**Comment by msgilligan** [comment]
An address with a `null` value for `before` implies that the address was created during the same block as the STO, right?

Note: We could probably remove or `@Ignore` this test for now as it's not clear it adds much value over the other tests. Unless of course, this anomalous behavior is in fact an issue with Omni Core...

**Comment by dexX7** [comment]
Yes, I think this is the case. While testing, I noticed the last time it failed, it had the same values (balance: 0.00033816, reserved: 0.10000000), but another address.

I agree to `@Ignore`, but I'm still curious. Are those tests executed in parallel, so state may overlap?

**Comment by dexX7** [comment]
Given that it's not used anymore, I'm going to close this.
