### ISSUE TITLE
Testing STO to a large number of owners

### ISSUE THREAD

**Issue by marv-engine** [msgilligan/bitcoin-spock#27]
Here's one way to test STO to hundreds or thousands of owners:

N existing owners each hold an integer number of divisible tokens and will receive .00000001 times the number of tokens they hold, so it will be easy to confirm they received the correct amount from the STO. The decimal portion of their balance after the STO will equal the integer portion, e.g. an address holding 1234.0 tokens before will now hold 1234.00001234 tokens after the STO.

1. The sending address starts with
 * (N(N+1)/2) * .00000001 divisible SP tokens to be sent
 * N * .00000001 TMSC for the fee
1. For i = 1 to N 
 * assign i tokens to the i-th address
   * the 1st address will have 1.0, 2nd will have 2.0, ..., the Nth address will have N.0
1. The sending address will use STO to send (N(N+1)/2) * .00000001 tokens
 * this is exactly the number of tokens owned by the sending address
1. The expected results are:
 * the sending address has 0.0 SP tokens
 * the sending address has 0.0 TMSC
 * each owner has (i + (i * .00000001)) tokens
   * the decimal portion of their balance after the STO will equal the integer portion

**Comment by dexX7** [comment]
Very nice, thanks!

The number of property units to create at the beginning would then be: ((n * (n + 1)) / 2) * 1.00000001

Let me test this...

**Comment by dexX7** [comment]
Now that's strange.. the test indeed fails for larger amounts. I added a bunch of debug output:

```
-----------------------------------------------------------------------
Send to 1 owers
-----------------------------------------------------------------------

Create a new divisible property with: 1.00000001 units

The actor starts with: 0.00000001 MSC
The actor starts with: 1.00000001 SPT

Owner #1 starts with: 1.0 SPT

Send to owners: 0.00000001

Owner #1 ends up with: 1.00000001 SPT (and should have: 1.00000001 SPT)

The actor ends up with: 0.00000000 MSC (should have 0.0 MSC)
The actor ends up with: 0.00000000 SPT (should have 0.0 SPT)


-----------------------------------------------------------------------
Send to 2 owers
-----------------------------------------------------------------------

Create a new divisible property with: 3.00000003 units

The actor starts with: 0.00000002 MSC
The actor starts with: 3.00000003 SPT

Owner #1 starts with: 1.0 SPT
Owner #2 starts with: 2.0 SPT

Send to owners: 0.00000003

Owner #1 ends up with: 1.00000001 SPT (and should have: 1.00000001 SPT)
Owner #2 ends up with: 2.00000002 SPT (and should have: 2.00000002 SPT)

The actor ends up with: 0.00000000 MSC (should have 0.0 MSC)
The actor ends up with: 0.00000000 SPT (should have 0.0 SPT)


-----------------------------------------------------------------------
Send to 100 owers
-----------------------------------------------------------------------

Create a new divisible property with: 5050.00005050 units

The actor starts with: 0.00000100 MSC
The actor starts with: 5050.00005050 SPT

Owner #1 starts with: 1.0 SPT
Owner #2 starts with: 2.0 SPT
Owner #3 starts with: 3.0 SPT
Owner #4 starts with: 4.0 SPT
Owner #5 starts with: 5.0 SPT
Owner #6 starts with: 6.0 SPT
Owner #7 starts with: 7.0 SPT
Owner #8 starts with: 8.0 SPT
Owner #9 starts with: 9.0 SPT
Owner #10 starts with: 10.0 SPT
Owner #11 starts with: 11.0 SPT
Owner #12 starts with: 12.0 SPT
Owner #13 starts with: 13.0 SPT
Owner #14 starts with: 14.0 SPT
Owner #15 starts with: 15.0 SPT
Owner #16 starts with: 16.0 SPT
Owner #17 starts with: 17.0 SPT
Owner #18 starts with: 18.0 SPT
Owner #19 starts with: 19.0 SPT
Owner #20 starts with: 20.0 SPT
Owner #21 starts with: 21.0 SPT
Owner #22 starts with: 22.0 SPT
Owner #23 starts with: 23.0 SPT
Owner #24 starts with: 24.0 SPT
Owner #25 starts with: 25.0 SPT
Owner #26 starts with: 26.0 SPT
Owner #27 starts with: 27.0 SPT
Owner #28 starts with: 28.0 SPT
Owner #29 starts with: 29.0 SPT
Owner #30 starts with: 30.0 SPT
Owner #31 starts with: 31.0 SPT
Owner #32 starts with: 32.0 SPT
Owner #33 starts with: 33.0 SPT
Owner #34 starts with: 34.0 SPT
Owner #35 starts with: 35.0 SPT
Owner #36 starts with: 36.0 SPT
Owner #37 starts with: 37.0 SPT
Owner #38 starts with: 38.0 SPT
Owner #39 starts with: 39.0 SPT
Owner #40 starts with: 40.0 SPT
Owner #41 starts with: 41.0 SPT
Owner #42 starts with: 42.0 SPT
Owner #43 starts with: 43.0 SPT
Owner #44 starts with: 44.0 SPT
Owner #45 starts with: 45.0 SPT
Owner #46 starts with: 46.0 SPT
Owner #47 starts with: 47.0 SPT
Owner #48 starts with: 48.0 SPT
Owner #49 starts with: 49.0 SPT
Owner #50 starts with: 50.0 SPT
Owner #51 starts with: 51.0 SPT
Owner #52 starts with: 52.0 SPT
Owner #53 starts with: 53.0 SPT
Owner #54 starts with: 54.0 SPT
Owner #55 starts with: 55.0 SPT
Owner #56 starts with: 56.0 SPT
Owner #57 starts with: 57.0 SPT
Owner #58 starts with: 58.0 SPT
Owner #59 starts with: 59.0 SPT
Owner #60 starts with: 60.0 SPT
Owner #61 starts with: 61.0 SPT
Owner #62 starts with: 62.0 SPT
Owner #63 starts with: 63.0 SPT
Owner #64 starts with: 64.0 SPT
Owner #65 starts with: 65.0 SPT
Owner #66 starts with: 66.0 SPT
Owner #67 starts with: 67.0 SPT
Owner #68 starts with: 68.0 SPT
Owner #69 starts with: 69.0 SPT
Owner #70 starts with: 70.0 SPT
Owner #71 starts with: 71.0 SPT
Owner #72 starts with: 72.0 SPT
Owner #73 starts with: 73.0 SPT
Owner #74 starts with: 74.0 SPT
Owner #75 starts with: 75.0 SPT
Owner #76 starts with: 76.0 SPT
Owner #77 starts with: 77.0 SPT
Owner #78 starts with: 78.0 SPT
Owner #79 starts with: 79.0 SPT
Owner #80 starts with: 80.0 SPT
Owner #81 starts with: 81.0 SPT
Owner #82 starts with: 82.0 SPT
Owner #83 starts with: 83.0 SPT
Owner #84 starts with: 84.0 SPT
Owner #85 starts with: 85.0 SPT
Owner #86 starts with: 86.0 SPT
Owner #87 starts with: 87.0 SPT
Owner #88 starts with: 88.0 SPT
Owner #89 starts with: 89.0 SPT
Owner #90 starts with: 90.0 SPT
Owner #91 starts with: 91.0 SPT
Owner #92 starts with: 92.0 SPT
Owner #93 starts with: 93.0 SPT
Owner #94 starts with: 94.0 SPT
Owner #95 starts with: 95.0 SPT
Owner #96 starts with: 96.0 SPT
Owner #97 starts with: 97.0 SPT
Owner #98 starts with: 98.0 SPT
Owner #99 starts with: 99.0 SPT
Owner #100 starts with: 100.0 SPT

Send to owners: 0.00005050

Owner #1 ends up with: 1.00000000 SPT (and should have: 1.00000001 SPT) <------ FAIL
Owner #2 ends up with: 2.00000000 SPT (and should have: 2.00000002 SPT) <------ FAIL
Owner #3 ends up with: 3.00000000 SPT (and should have: 3.00000003 SPT) <------ FAIL
Owner #4 ends up with: 4.00000003 SPT (and should have: 4.00000004 SPT) <------ FAIL
Owner #5 ends up with: 5.00000005 SPT (and should have: 5.00000005 SPT)
Owner #6 ends up with: 6.00000006 SPT (and should have: 6.00000006 SPT)
Owner #7 ends up with: 7.00000007 SPT (and should have: 7.00000007 SPT)
Owner #8 ends up with: 8.00000008 SPT (and should have: 8.00000008 SPT)
Owner #9 ends up with: 9.00000009 SPT (and should have: 9.00000009 SPT)
Owner #10 ends up with: 10.00000010 SPT (and should have: 10.00000010 SPT)
Owner #11 ends up with: 11.00000012 SPT (and should have: 11.00000011 SPT)
Owner #12 ends up with: 12.00000012 SPT (and should have: 12.00000012 SPT)
Owner #13 ends up with: 13.00000013 SPT (and should have: 13.00000013 SPT)
Owner #14 ends up with: 14.00000014 SPT (and should have: 14.00000014 SPT)
Owner #15 ends up with: 15.00000015 SPT (and should have: 15.00000015 SPT)
Owner #16 ends up with: 16.00000016 SPT (and should have: 16.00000016 SPT)
Owner #17 ends up with: 17.00000017 SPT (and should have: 17.00000017 SPT)
Owner #18 ends up with: 18.00000018 SPT (and should have: 18.00000018 SPT)
Owner #19 ends up with: 19.00000019 SPT (and should have: 19.00000019 SPT)
Owner #20 ends up with: 20.00000020 SPT (and should have: 20.00000020 SPT)
Owner #21 ends up with: 21.00000021 SPT (and should have: 21.00000021 SPT)
Owner #22 ends up with: 22.00000023 SPT (and should have: 22.00000022 SPT)
Owner #23 ends up with: 23.00000023 SPT (and should have: 23.00000023 SPT)
Owner #24 ends up with: 24.00000024 SPT (and should have: 24.00000024 SPT)
Owner #25 ends up with: 25.00000025 SPT (and should have: 25.00000025 SPT)
Owner #26 ends up with: 26.00000026 SPT (and should have: 26.00000026 SPT)
Owner #27 ends up with: 27.00000028 SPT (and should have: 27.00000027 SPT)
Owner #28 ends up with: 28.00000028 SPT (and should have: 28.00000028 SPT)
Owner #29 ends up with: 29.00000029 SPT (and should have: 29.00000029 SPT)
Owner #30 ends up with: 30.00000030 SPT (and should have: 30.00000030 SPT)
Owner #31 ends up with: 31.00000031 SPT (and should have: 31.00000031 SPT)
Owner #32 ends up with: 32.00000032 SPT (and should have: 32.00000032 SPT)
Owner #33 ends up with: 33.00000033 SPT (and should have: 33.00000033 SPT)
Owner #34 ends up with: 34.00000034 SPT (and should have: 34.00000034 SPT)
Owner #35 ends up with: 35.00000035 SPT (and should have: 35.00000035 SPT)
Owner #36 ends up with: 36.00000036 SPT (and should have: 36.00000036 SPT)
Owner #37 ends up with: 37.00000037 SPT (and should have: 37.00000037 SPT)
Owner #38 ends up with: 38.00000038 SPT (and should have: 38.00000038 SPT)
Owner #39 ends up with: 39.00000039 SPT (and should have: 39.00000039 SPT)
Owner #40 ends up with: 40.00000040 SPT (and should have: 40.00000040 SPT)
Owner #41 ends up with: 41.00000041 SPT (and should have: 41.00000041 SPT)
Owner #42 ends up with: 42.00000042 SPT (and should have: 42.00000042 SPT)
Owner #43 ends up with: 43.00000043 SPT (and should have: 43.00000043 SPT)
Owner #44 ends up with: 44.00000045 SPT (and should have: 44.00000044 SPT)
Owner #45 ends up with: 45.00000045 SPT (and should have: 45.00000045 SPT)
Owner #46 ends up with: 46.00000046 SPT (and should have: 46.00000046 SPT)
Owner #47 ends up with: 47.00000047 SPT (and should have: 47.00000047 SPT)
Owner #48 ends up with: 48.00000048 SPT (and should have: 48.00000048 SPT)
Owner #49 ends up with: 49.00000049 SPT (and should have: 49.00000049 SPT)
Owner #50 ends up with: 50.00000050 SPT (and should have: 50.00000050 SPT)
Owner #51 ends up with: 51.00000051 SPT (and should have: 51.00000051 SPT)
Owner #52 ends up with: 52.00000052 SPT (and should have: 52.00000052 SPT)
Owner #53 ends up with: 53.00000053 SPT (and should have: 53.00000053 SPT)
Owner #54 ends up with: 54.00000055 SPT (and should have: 54.00000054 SPT)
Owner #55 ends up with: 55.00000055 SPT (and should have: 55.00000055 SPT)
Owner #56 ends up with: 56.00000056 SPT (and should have: 56.00000056 SPT)
Owner #57 ends up with: 57.00000057 SPT (and should have: 57.00000057 SPT)
Owner #58 ends up with: 58.00000058 SPT (and should have: 58.00000058 SPT)
Owner #59 ends up with: 59.00000059 SPT (and should have: 59.00000059 SPT)
Owner #60 ends up with: 60.00000060 SPT (and should have: 60.00000060 SPT)
Owner #61 ends up with: 61.00000061 SPT (and should have: 61.00000061 SPT)
Owner #62 ends up with: 62.00000062 SPT (and should have: 62.00000062 SPT)
Owner #63 ends up with: 63.00000063 SPT (and should have: 63.00000063 SPT)
Owner #64 ends up with: 64.00000064 SPT (and should have: 64.00000064 SPT)
Owner #65 ends up with: 65.00000065 SPT (and should have: 65.00000065 SPT)
Owner #66 ends up with: 66.00000066 SPT (and should have: 66.00000066 SPT)
Owner #67 ends up with: 67.00000067 SPT (and should have: 67.00000067 SPT)
Owner #68 ends up with: 68.00000068 SPT (and should have: 68.00000068 SPT)
Owner #69 ends up with: 69.00000069 SPT (and should have: 69.00000069 SPT)
Owner #70 ends up with: 70.00000070 SPT (and should have: 70.00000070 SPT)
Owner #71 ends up with: 71.00000071 SPT (and should have: 71.00000071 SPT)
Owner #72 ends up with: 72.00000072 SPT (and should have: 72.00000072 SPT)
Owner #73 ends up with: 73.00000073 SPT (and should have: 73.00000073 SPT)
Owner #74 ends up with: 74.00000074 SPT (and should have: 74.00000074 SPT)
Owner #75 ends up with: 75.00000075 SPT (and should have: 75.00000075 SPT)
Owner #76 ends up with: 76.00000076 SPT (and should have: 76.00000076 SPT)
Owner #77 ends up with: 77.00000077 SPT (and should have: 77.00000077 SPT)
Owner #78 ends up with: 78.00000078 SPT (and should have: 78.00000078 SPT)
Owner #79 ends up with: 79.00000079 SPT (and should have: 79.00000079 SPT)
Owner #80 ends up with: 80.00000080 SPT (and should have: 80.00000080 SPT)
Owner #81 ends up with: 81.00000081 SPT (and should have: 81.00000081 SPT)
Owner #82 ends up with: 82.00000082 SPT (and should have: 82.00000082 SPT)
Owner #83 ends up with: 83.00000083 SPT (and should have: 83.00000083 SPT)
Owner #84 ends up with: 84.00000084 SPT (and should have: 84.00000084 SPT)
Owner #85 ends up with: 85.00000085 SPT (and should have: 85.00000085 SPT)
Owner #86 ends up with: 86.00000086 SPT (and should have: 86.00000086 SPT)
Owner #87 ends up with: 87.00000088 SPT (and should have: 87.00000087 SPT)
Owner #88 ends up with: 88.00000089 SPT (and should have: 88.00000088 SPT)
Owner #89 ends up with: 89.00000089 SPT (and should have: 89.00000089 SPT)
Owner #90 ends up with: 90.00000090 SPT (and should have: 90.00000090 SPT)
Owner #91 ends up with: 91.00000091 SPT (and should have: 91.00000091 SPT)
Owner #92 ends up with: 92.00000092 SPT (and should have: 92.00000092 SPT)
Owner #93 ends up with: 93.00000093 SPT (and should have: 93.00000093 SPT)
Owner #94 ends up with: 94.00000094 SPT (and should have: 94.00000094 SPT)
Owner #95 ends up with: 95.00000095 SPT (and should have: 95.00000095 SPT)
Owner #96 ends up with: 96.00000096 SPT (and should have: 96.00000096 SPT)
Owner #97 ends up with: 97.00000097 SPT (and should have: 97.00000097 SPT)
Owner #98 ends up with: 98.00000098 SPT (and should have: 98.00000098 SPT)
Owner #99 ends up with: 99.00000099 SPT (and should have: 99.00000099 SPT)
Owner #100 ends up with: 100.00000100 SPT (and should have: 100.00000100 SPT)

The actor ends up with: 0.00000003 MSC (should have 0.0 MSC)
The actor ends up with: 0.00000000 SPT (should have 0.0 SPT)


Condition not satisfied:

finalBalanceMSC.balance == 0.0
|               |       |
|               3E-8    false
foundation.omni.rpc.MPBalanceEntry@58bb59

Condition not satisfied:

finalBalanceMSC.balance == 0.0
|               |       |
|               3E-8    false
foundation.omni.rpc.MPBalanceEntry@58bb59

	at foundation.omni.test.rpc.sto.MSCSendToOwnersSpec.Send to a very large number of owners(MSCSendToOwnersSpec.groovy:202)
```

**Comment by marv-engine** [comment]
@dexX7 See owner 11, 22, 27. They have 1 more willet than they should, but they're not detected as errors. I expect it has to do with rounding up in the calculations. I thought there should be no rounding problems with the test set up this way.

**Comment by marv-engine** [comment]
Also, 87 & 88 got 1 more willet than they should have. There should be a total of 7 extra willets that were assigned incorrectly.

**Comment by dexX7** [comment]
I looped more than once to print the results, then do the checks. This is the reason why it didn't fail earlier. I updated the post above with more information.

**Comment by marv-engine** [comment]
54 & 44 also got 1 more than they should. So, there are 7 owners who each received 1 extra willet. That's why owners 1,2 and 3 each got 0 and owner 4 got only 3.

**Comment by zathras-crypto** [comment]
Hey DexX, was nosing around your repo - have you committed this test at all?
Sorry for spam just gonna paste in some skype chat here...

[7:56:35 AM] M. Sean Gilligan: Looks like we've also got some preliminary results from a large STO transaction and are seeing some errors
[7:56:45 AM] zathrasc: awesome :)
[7:56:46 AM] M. Sean Gilligan: This is "hot off the press"
[7:57:09 AM] zathrasc: errors can mean a bug, and finding a bug before release is always awesome :)
[7:57:36 AM] Adam Chamely: Sean are these on blockchain tests or in local enviroments
[7:57:43 AM] M. Sean Gilligan: Also, I should mention that we found some errors in the spreadsheet data itself, which were corrected.
[7:57:48 AM] zathrasc: @Adam, regtesting mate I believe
[7:57:58 AM] M. Sean Gilligan: This is RegTest
[7:58:00 AM] Adam Chamely: Thats what i thought just wanted to confirm
[7:58:04 AM] zathrasc: so are we talking math errors (as in calculation)?
[7:58:08 AM] M. Sean Gilligan: See Issue #27: https://github.com/msgilligan/bitcoin-spock/issues/27
[7:58:38 AM] zathrasc: looking
[7:58:59 AM] M. Sean Gilligan: Yeah, it looks like some sends are rounding up unexpectedly which are causing others to round down unexpectedly
[8:01:30 AM] zathrasc: interesting
[8:01:42 AM] zathrasc: rounding is applied as per spec
[8:03:23 AM] zathrasc: [specquote]
[8:04:03 AM] zathrasc: could you mention to DexX to add some debugging printf's for the intermediate values used in the calculation, and rerun the test pumping out all the intermed values inbetween - then we can see exactly what is being done with the numbers
[8:05:02 AM] M. Sean Gilligan: The address being "shortchanged" is logically following the Spec, but what we don't understand is why the other addresses are rounding up
[8:05:21 AM] zathrasc: that's why we need the intermed values
[8:05:31 AM] zathrasc: so...
[8:05:32 AM] zathrasc: for example
[8:05:34 AM] zathrasc: let's see
[8:05:36 AM] M. Sean Gilligan: Which intermediate values?
[8:05:38 AM] zathrasc:  int64_t totalTokens = getTotalTokens(property);
 file_log("\t    Total Tokens: %s\n", FormatMP(property, totalTokens).c_str());
[8:05:48 AM] zathrasc: so we can make sure the total count of tokens is accurate
[8:05:51 AM] zathrasc: let's also see
[8:06:25 AM] zathrasc:   // does the sender have enough of the property he's trying to "Send To Owners" ?
      if (getMPbalance(sender, property, BALANCE) < (int64_t)nValue)
      {
        return (PKT_ERROR_STO -3);
      }
add a printf for the senders balance here so we can see if it is exactly as expected
[8:07:00 AM] zathrasc: add printf's for these values here
[8:07:00 AM] zathrasc:     percentage = (double) owns / (double) totalTokens;
        piece = percentage * nValue;
        should_receive = ceil(piece);
[8:07:34 AM] zathrasc: printf for will_really_receive var too
[8:08:11 AM] zathrasc: basically by outputting all of those intermediary calculations used to generate the amount distributed to a given address, we can see where the numbers are getting tripped up
[8:09:17 AM] zathrasc: so two options really - 1) DexX adds those to his existing tests, or 2) DexX flips me whatever I need to recreate the test and I can modify the code for extra debugging and rerun myself
[8:10:09 AM] M. Sean Gilligan: Yeah, we probably mentioned this a little too soon
[8:11:15 AM] zathrasc: my eye is instantly drawn here - should_receive = ceil(piece); as ceil is always roundup whereas round is roundup/down but without seeing the intermed numbers it's hard to tell
[8:12:02 AM] zathrasc: actually looking at spec we are always supposed to round up
[8:12:15 AM] zathrasc: so perhaps non issue
[8:12:36 AM] zathrasc: yeah - more info will help, let me know about the extra debugging stuff and if I can help at all
[8:12:39 AM] zathrasc: good find though :)
[8:13:14 AM] M. Sean Gilligan: My guess is this isn't a Spock test yet
[8:13:27 AM] M. Sean Gilligan: We'll add it to the test suite
[8:13:41 AM] M. Sean Gilligan: Then you can run locally as before
[8:13:42 AM] zathrasc: let me check DexX's private repo, he might have committed the test

**Comment by dexX7** [comment]
Sorry, it's still a bit messy, but here you go:

https://github.com/msgilligan/bitcoin-spock/pull/28

It begins to fail with 65 owners.

**Comment by dexX7** [comment]
As expected:

```
2015-01-23 22:10:02     6500000000 = n4qvtpWDoU7k4paYTUGsjLxjNZ6pbWoNSf, perc=         0.0303030303, piece=        65.0000000000, should_get=             65, will_really_get=             65, sent_so_far=             65
2015-01-23 22:10:02     piece accurate: 65.00000000000000000000000000000000000000000000000000
2015-01-23 22:10:02     percentage accurate: 0.03030303030303030387138107926148222759366035461426

2015-01-23 22:10:02     6400000000 = n4cLsdGTuxrnwxMYZoaqEuWciLaHDyZNFy, perc=         0.0298368298, piece=        64.0000000000, should_get=             64, will_really_get=             64, sent_so_far=            129
2015-01-23 22:10:02     piece accurate: 64.00000000000000000000000000000000000000000000000000
2015-01-23 22:10:02     percentage accurate: 0.02983682983682983680395750525349285453557968139648

2015-01-23 22:10:02     6300000000 = n4V3qiRUANYYzSbWxhbToyLZQ1vsjaF2yT, perc=         0.0293706294, piece=        63.0000000000, should_get=             63, will_really_get=             63, sent_so_far=            192
2015-01-23 22:10:02     piece accurate: 63.00000000000000000000000000000000000000000000000000
2015-01-23 22:10:02     percentage accurate: 0.02937062937062936973653393124550348147749900817871

2015-01-23 22:10:02     6200000000 = n4N9kMg8vAF8kQy1MeroThdfg61FcoP3Nn, perc=         0.0289044289, piece=        62.0000000000, should_get=             63, will_really_get=             63, sent_so_far=            255
2015-01-23 22:10:02     piece accurate: 62.00000000000000710542735760100185871124267578125000
2015-01-23 22:10:02     percentage accurate: 0.02890442890442890613855730919112829724326729774475
```

**Comment by msgilligan** [comment]
The tests are now active on [ci.omni.foundation](http://ci.omni.foundation) and you can see they failed on the [report for Job #208](http://ci.omni.foundation/job/msc-integ-regtest/208/testReport/)

Thanks, @dexX7 !

**Comment by dexX7** [comment]
So FWIW: I tested MC with the approach as outlined in the issue one above, and this STO test works fine, even with 5000+ owners.

**Comment by marv-engine** [comment]
To get additional test cases, it's probably worthwhile testing where users start with satoshis and the STO is for 100,000,000 times what they have, e.g. user 1 has 0.00000001 and will receive 1.0. This could be done with indivisible as well, so user 1starts with 1 and receives 100,000,000.

Also might be revealing to use factors of 2, 3, 4, 5, .5, .333..., .25, .2 of what each recipient starts with.

**Comment by dexX7** [comment]
Great idea. We basically have two numbers to tweak: a start amount and an amount to distribute. Is there any limit, besides avoiding to create more units that can be, namely `9223372036854775807`?

The total fee should be: `maxN * feePerAddress`
The units to create: `((maxN * (maxN + 1)) / 2) * (START + DISTRIBUTE)`
The starting balance of an owner: `START * n`
The amount an owner receives: `DISTRIBUTE * n`
The final balance an owner should have: `(START + DISTRIBUTE) * n`

**Comment by marv-engine** [comment]
The only constraint that comes to mind is to use numbers that can be easily checked by hand and whose results are easy to recognize visually.

**Comment by dexX7** [comment]
This was mostly addressed in https://github.com/msgilligan/bitcoin-spock/commit/c869530edf6069c6d0e94ce0bb6823d34e16c649. Anything else you have in mind?

**Comment by marv-engine** [comment]
It would be good to test rounding up with a large number of owners, but I haven't figured out an algorithm to do it so it can be programmatically checked for correctness.

**Comment by dexX7** [comment]
I really like how the "send to many owners" tests were created and something similar for rounding would be great, but I'm wondering, if there is any difference between 3 or 30000 owners at all, and if rounding might already be covered by the "unequal" tests of the test plan?

**Comment by marv-engine** [comment]
I had the same thought, but it would give us (me?) more confidence that rounding will work for a large set of owners, or it might uncover something unexpected like we saw the other day.

**Comment by dexX7** [comment]
True, even though it was sort of forseeable, I didn't expect it either. In general I think the more tests there are, the better.

**Comment by msgilligan** [comment]
I've suggested elsewhere that the core STO calculation (division and multiplication) should be extracted to a separate method and various corner cases (of rounding) could be tested directly by Boost unit tests.

**Comment by msgilligan** [comment]
Any reason *not* to close this issue now?

**Comment by dexX7** [comment]
I'd say: go ahead. @marv-engine: if you come up with another test, let me know.
