### ISSUE TITLE
Groovydoc is broken for com.msgilligan.bitcoin.rpc.BitcoinClient

### ISSUE THREAD

**Issue by msgilligan** [msgilligan/bitcoin-spock#3]
Commit c9cc26b48616ce46772ee0d2fbae735d351a146c introduced some code that appears to be causing GroovyDoc to fail for this class. We need to workaround this problem somehow so that `BitcoinClient` can have API docs generated -- and so the Jenkins publish JavaDocs step will succeed.

**Comment by msgilligan** [comment]
Commit 38220d85197e433089b10b58ae32489687f6657d allows the build to complete, but the JavaDocs still aren't being published properly.

**Comment by msgilligan** [comment]
The fix is likely to be one of the following:

1. Make a minor change to the code to avoid the bug in the documentation tool
1. Use JavaDoc for Java code and GroovyDoc for Groovy code
1. Use a new version of GroovyDoc that fixes the bug.

**Comment by dexX7** [comment]
Hey there, I noticed the failing docs, too, but I assumed it's my environment. You were right, the following code is to blame:

[BitcoinClient.java#L433-L440](https://github.com/dexX7/bitcoin-spock/blob/9e907ebfe4effc7c5c9ae90792db173e361ae1a1/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java#L433-L440):

```java
private <T> List<String> applyToString(Iterable<T> elements) {
    List<String> stringList = new ArrayList<>();
    for (T element : elements) {
        String elementAsString = element.toString();
        stringList.add(elementAsString);
    }
    return stringList;
}
```

Using `Address` as type doesn't do the trick, and it looks like this is actually the cause.

**Comment by msgilligan** [comment]
Actually there are known problems with running GroovyDoc on some Java 7 constructs. I applied a workaround that is more targeted and lets us keep using `[ address ]`:
https://github.com/msgilligan/bitcoin-spock/commit/c082df41efff0e1caed5907fa9ecb02fad05c65e
