### ISSUE TITLE
CurrencyID and Bitcoin

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#34]
While I wanted to create a test of the STO invalidation for Bitcoin, I noticed this is difficult, because the range of CurrencyID starts with 1.

I'm going to change this to 0, because there are also other places where it would be of value, if the CurrencyID class could be used.

Another idea I had in mind was to create a subclass of CurrencyID, solely for Bitcoin.

Are there alternatives?

**Comment by msgilligan** [comment]
Adding zero sounds like a reasonable approach - as long as we verify that every method that takes a CurrencyID properly handles the case of CurrencyID = 0.

**Comment by msgilligan** [comment]
Fixed in PR #36.
