### ISSUE TITLE
Update to bitcoinj 0.12.x

### ISSUE THREAD

**Issue by msgilligan** [msgilligan/bitcoin-spock#42]
See [bitcoinj 0.12.1 release notes](https://bitcoinj.github.io/release-notes#version-0121)

*Note:* There is actually a 0.12.2 release that's not mentioned on the website or in the release notes!

The main reason is to just keep up with bug fixes from bitcoinj, but it will also give us a chance to experiment with the new `Coin` class and figure out how that relates to potential Omni "amount" classes and or the new JavaMoney API.

**Comment by msgilligan** [comment]
Commit 3c0a39440102dc93f859c4d6146a95d2360c3b4b upgraded to 12.2, but there are two minor issues mentioned in the comment for that commit.

**Comment by msgilligan** [comment]
@dexX7 Any ideas on either of the two issues (especially the first) mentioned in the commit?

**Comment by msgilligan** [comment]
Commit 851938505dbe674e90e43a28eb18559a00e1be8c resolves the second minor issue (bitcoinj ECKey changes breaking some tests)

**Comment by msgilligan** [comment]
The remaining issue with transaction fees isn't directly related to the bitcoinj upgrade, so I'm going to close this issue.

**Comment by dexX7** [comment]
@msgilligan: Awesome work! I'll take a look at it shortly. I have some ideas already. :)
