### ISSUE TITLE
"Transaction too large" error

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#50]
I need to dig deeper in the actual issue. Sure, we could ban all uses of where we don't construct BTC transactions ourself (special note: there is no check either, but given the funding with coinbase coins, it's less likely to hit a maximum), but this doesn't feel right.

It needs to be investigated what causes the error and how to fix it (upstream?) or how to avoid causing it.

**Comment by dexX7** [comment]
I identified the core problem, and right now we have to deal with it on our own, see: https://github.com/bitcoin/bitcoin/issues/5782

A possible solution could be to use a garbage/dust collector after each regtest, to minimize the overall number of unspent outputs. I'll give it a try and update soon.

**Comment by msgilligan** [comment]
Nice work, @dexX7 ! Closing...

**Comment by dexX7** [comment]
Yup! :) Although this is only a workaround and not side-effect free, but for now this is probably the easiest way to handle it on a larger scale. When doing crazy tests, say for example running "send to many owners" with 30000 recipients, we'd need to insert a manual sweep within the test.

Quick question:
```groovy
@see foundation.omni.BaseRegTestSpec#cleanup()
```
... was not recognized as valid Java/Groovy doc reference. Do you have an idea why, by any chance?

**Comment by msgilligan** [comment]
Probably because `foundation.omni.BaseRegTestSpec` is in the `integ` test directory and API docs are not being published for the tests.
