### ISSUE TITLE
Remove unused or depreciated tests

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#57]
In particular I was thinking about:

- `foundation.omni.test.exodus.ExodusFundraiserSpec` (duplicate of `MoneyManSpec`?)
- `foundation.omni.test.exodus.FaizSpec`

I'm not sure about:

- `com.msgilligan.bitcoin.rpc.RegTestSendManySpec` (uses account system, ignored)
- `foundation.omni.test.rpc.sto.SendToOwnersConsensusComparisonSpec` (ignored)

**Comment by msgilligan** [comment]
`ExodusFundraiserSpec` was written before the "MoneyMan" behavior was implemented. I was thinking that in RegTest mode we'd have to recreate the Exodus fundraiser period to create initial MSC balances, etc. This was a test that would drive that and verify correct operation.

`FaizSpec` was created as a demo for Faiz around the same time.

`RegTestSendManySpec` was created to demonstrate a bug (bugs?) in the Bitcoin Core account system - it can be deleted, I think. There's not point in submitting this upstream, right?

`SendToOwnersConsensusComparisonSpec` was an experiment that can be deleted.

**Comment by msgilligan** [comment]
Removed in commit 8510657f3141a69aa08e10d94b25777c8f3bea93.

**Comment by dexX7** [comment]
> There's not point in submitting this upstream, right?

No, the accounting system is considered as broken, well, at least based on common sense, and it is already tagged as "depreciated" in Bitcoin Core 0.10 and probably going to be turned into an "address labeling" system.

I'm fine with the deletes. :)
