### ISSUE TITLE
Bitcoin Core 0.10 incompability: setgenerate

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#60]
The tests:

> com.msgilligan.bitcoin.cli.BitcoinJCliSpec: "generate a block"
> com.msgilligan.bitcoin.rpc.DynamicRPCClientSpec: "setgenerate"

... fail, when using Bitcoin Core 0.10, because `setgenerate` doesn't return `null` anymore, but a list of block hashes.

**Comment by msgilligan** [comment]
`setgenerate` was probably a poor choice for testing the case of a method that returns `null`.

I don't have 0.10 handy today, but will try to fix.

**Comment by msgilligan** [comment]
This should be fixed in ac468eeb4443d013b4cd3da6a5ae11e34806eb24.

@dexX7 can you please verify and close this issue if it is fixed?

**Comment by dexX7** [comment]
Confirmed, works fine now.

**Comment by msgilligan** [comment]
Thanks!
