### ISSUE TITLE
Caution: createFundedAddress fails for very small MSC amounts

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#7]
When trying to fund an address with an amount that has the last two digits set, it fails.

For example:
```groovy
createFundedAddress(1.00000000, 0.00000010)
createFundedAddress(1.00000000, 0.00000001)
createFundedAddress(1.00000000, 1.00000010)
...
```

This is because creating 10 willets would require a BTC payment of 0.0000000**0**1 BTC.

**Comment by msgilligan** [comment]
I should either remove the two `assert` statements that check `MSC` and `TMSC` balances near the end of the method or adjust them to account for rounding.

**Comment by msgilligan** [comment]
I now see my above comment misses the point. There are tests where we need to fund an address with an amount with 1 willet precision.

**Comment by msgilligan** [comment]
So there are a couple of approaches (that quickly come to mind) for funding an address with 1-willet precision:

1. Create a disposable intermediate address and then transfer the exact amount to the real funded address which is returned. (Requires 2 `generateBlock` calls?)
1. Send the rounded-up amount via "money man" to the funded address and then send the extra coins away. (Requires 2 `generateBlock` calls?)
1. Have a reserved system-wide address that is kept well-funded (i.e. a long-lived, permanent intermediate address) and send coins to the new funded address from this address. (Should work with a single `generateBlock` call provided the reserved address already has the necessary funds.)
